---
- name: Install Apache and upload webpage
  hosts: all 
  become: true

  vars:
    source_file: ./MyWebSite/index.html
    destination: /var/www/html 

  tasks:
    - name: Check OS family
      debug: var=ansible_os_family

    - block:       # ========== for RedHat =================
      
      - name: Install Apache on CentOS
        yum: name=httpd state=latest

      - name: Copy HomePage ot server
        copy: src={{ source_file }} dest={{ destination }} mode=0555
        notify: Restart Apache RedHat

      - name: Start server and enable it (CentOS)
        service: name=httpd state=started enabled=yes

      when: ansible_os_family=="RedHat"

    - block:       # ========== for Debian =================

      - name: Install Apache on Ubuntu
        apt: name=apache2 state=latest

      - name: Copy HomePage ot server
        copy: src={{ source_file }} dest={{ destination }} mode=0555
        notify: Restart Apache Debian

      - name: Start server and enable it (Ubuntu)
        service: name=apache2 state=started enabled=yes

      when: ansible_os_family=="Debian"

    
  handlers:
    - name: Restart Apache RedHat
      service: name=httpd state=restarted

    - name: Restart Apache Debian 
      service: name=apache2 state=restarted       
