---
- name: Install Apache WebServer
  become: true
  hosts: centos

  tasks:
    - name: Install Apache
      yum: name=httpd state=latest

    - name: Start and enable Apache
      service: name=httpd state=started enabled=yes

